language: php

php:
  - 7.2
  - 7.4

services:
  - postgresql
  - mysql

env:
  matrix:
    - DB=mysql db_dsn='mysql://root@127.0.0.1/cakephp_test'
    - DB=pgsql db_dsn='postgres://postgres@127.0.0.1/cakephp_test'
    - DB=sqlite db_dsn='sqlite:///:memory:'

  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.4
      env: CHECKS=1 DEFAULT=0

    - php: 7.2
      env: PREFER_LOWEST=1

    - php: 7.3
      env: COVERAGE=1 DEFAULT=0 DB=mysql db_dsn='mysql://root@127.0.0.1/cakephp_test'

before_script:
  - if [[ $COVERAGE != 1 ]]; then phpenv config-rm xdebug.ini; fi

  - if [[ $PREFER_LOWEST != 1 ]]; then composer install --no-interaction ; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-lowest --prefer-stable --no-interaction ; fi

  - if [[ $CHECKS == 1 ]]; then composer stan-setup; fi

  - if [[ $DB == 'mysql' ]]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi
  - if [[ $DB == 'pgsql' ]]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $COVERAGE == 1 ]]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi

  - if [[ $CHECKS == 1 ]]; then composer cs-check; fi
  - if [[ $CHECKS == 1 ]]; then composer stan; fi

after_success:
  - if [[ $COVERAGE == 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
